[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Tell Netlify secret scanner to ignore public client keys
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_TMDB_BASE_URL,NEXT_PUBLIC_TMDB_API_KEY,NEXT_PUBLIC_TMDB_IMAGE_BASE,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"
